import java.util.Arrays;
import exercices.tp;
class Main {
  public static void main(String[] args) {
    int[] tab = {5,2,8,9,7};
    int[][] tab2d = {{5,2,8},{9,7,4}};
    int[] copyTab = {5,2,8,9,7};
    int[][] copyTab2d = {{5,2,8},{9,7,4}};
    System.out.println("Tab One Dimension Length: "+tab.length);
    System.out.println("Tab Two Dimension Length: "+tab2d.length);
    System.out.println(tp.exercice13(5));
    System.out.print("Exercice 1 : ");
    tp.exercice1();
    System.out.println();
    System.out.print("Exercice 2 : ");
    tp.exercice2();
    System.out.println();
    System.out.print("Exercice 3 : ");
    tp.exercice3(tab);
    tab = copyTab;
    System.out.println();
    System.out.print("Exercice 4 : ");
    tp.exercice4(tab);
    tab = copyTab;
    System.out.println();
    System.out.print("Exercice 5 : ");
    tp.exercice5(tab);
    tab = copyTab;
    System.out.println();
    System.out.print("Exercice 6 : ");
    tp.exercice6(tab);
    tab = copyTab;
    System.out.println();
    System.out.print("Exercice 7 : ");
    tp.exercice7(tab);
    tab = copyTab;
    System.out.println();
    System.out.print("Exercice 8 : ");
    tp.exercice8(tab2d);
    tab2d = copyTab2d;
    System.out.println();
    System.out.print("Exercice 9 : ");
    tp.exercice9(tab2d);
    tab2d = copyTab2d;
    System.out.println();
    System.out.print("Exercice 10 : ");
    System.out.print("Index out of array");
    //tp.exercice10(tab2d);
    tab2d = copyTab2d;
    System.out.println();
    System.out.print("Exercice 11 : ");
    tp.exercice11(tab2d);
    tab2d = copyTab2d;
    System.out.println();
    System.out.print("Exercice 12 : ");
    tp.exercice12(tab2d);
    tab2d = copyTab2d;
    System.out.println();
    System.out.print("Exercice 13 : ");
    System.out.print(tp.exercice13(5));
    System.out.println();
    System.out.print("Exercice 14 : ");
    tp.exercice14(2,0,5);
    System.out.println();
    System.out.print("Exercice 15 : ");
    System.out.print(tp.exercice15(5));
    System.out.println();
    
  }
}